eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    eureka-service-url-poll-interval-seconds: 30
spring:
  cloud:
    config:
      override.system-properties: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/nuvine

logging:
  level:
    root: INFO
    com.baskaaleksander.nuvine: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: WARN