eureka:
  instance:
    hostname: discovery
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}

application:
  frontend-url: ${FRONTEND_URL}
  config:
    api-base-url: http://gateway:8222/api/v1
