services:
  postgres:
    container_name: ms_postgres
    image: postgres:17
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped
  mongodb:
    container_name: ms_mongodb
    image: mongo:6
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - microservices-net
    restart: unless-stopped

  keycloak:
    container_name: ms_keycloak
    image: quay.io/keycloak/keycloak:26.4.4
    env_file:
      - .env
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}

      KC_DB: ${KC_DB}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE}
    ports:
      - "9098:8080"
    networks:
      - microservices-net
    command:
      - start-dev
    volumes:
      - keycloak:/opt/keycloak/data
    restart: unless-stopped
  kafka:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka-kraft
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CLUSTER_ID: "abcdefghijklmnopqrstuv"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-kraft:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    restart: unless-stopped

  minio:
    container_name: ms_minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_NAME}
      MINIO_ROOT_PASSWORD: ${MINIO_ACCESS_SECRET}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    networks:
      - microservices-net
    restart: unless-stopped

  qdrant:
    container_name: ms_qdrant
    image: qdrant/qdrant:latest
    env_file:
      - .env
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant:/qdrant/storage
    networks:
      - microservices-net
    restart: unless-stopped

  prometheus:
    container_name: ms_prometheus
    image: prom/prometheus:latest
    env_file:
      - .env
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    networks:
      - microservices-net
    restart: unless-stopped

  grafana:
    container_name: ms_grafana
    image: grafana/grafana:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - microservices-net
    restart: unless-stopped

  redis:
    container_name: ms_redis
    image: redis:8.4.0
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass "${REDIS_PASSWORD}" --appendonly yes
    networks:
      - microservices-net
    volumes:
      - redis:/data

  zipkin:
    container_name: ms_zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - microservices-net
    volumes:
      - zipkin:/data
    restart: unless-stopped


networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  mongodb:
  keycloak:
  minio:
  qdrant:
  prometheus:
  grafana:
  redis:
  zipkin:
